# Solution 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
timer_start = Time.now

a = [1,2]
sum = 0

while a.last < 4000000 do
  if a.last.even?
    sum += a.last

  a << a.first + a.last
  a.shift
end

puts a.last
puts "Elapsed Time: #{(Time.now - timer_start)*1000} milliseconds"